import {
  faAddressCard,
  faArrowTrendUp,
  faBoxArchive,
  faFileInvoice,
  faFolderOpen,
  faHeadset,
  faIdBadge,
  faLayerGroup,
  faCalendarDays,
  faBell,
  faPlus,
  faRotate,
  faTriangleExclamation,
} from "@fortawesome/free-solid-svg-icons";

export const primaryNavItems = [
  { label: "Dashboard", href: "/", icon: faArrowTrendUp },
  { label: "Create Tickets", href: "/tickets/create", icon: faPlus },
  { label: "Tickets", href: "/tickets", icon: faFileInvoice },
  { label: "Spill over", href: "/spill-over", icon: faTriangleExclamation },
  { label: "Ledgers", href: "/ledgers", icon: faLayerGroup },
  { label: "Period", href: "/periods", icon: faCalendarDays },
  { label: "Export", href: "/export-ledger", icon: faFolderOpen },
  { label: "Archive", href: "/archive", icon: faBoxArchive },
  { label: "Repeat Tickets", href: "/repeat-tickets", icon: faRotate },
  { label: "Admin Panel", href: "/admin", icon: faAddressCard },
  { label: "Profile", href: "/profile", icon: faIdBadge },
  { label: "Notifications", href: "/notifications", icon: faBell },
  { label: "Customer Service", href: "/contact-support", icon: faHeadset },
] as const;
