# Generated by Django 4.2.28 on 2026-02-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_overflow_amount_to_approve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overflow",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overflows",
                to="core.transaction",
            ),
        ),
    ]
