# Generated by Django 4.2.28 on 2026-04-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ledger_is_capacity_reserve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identifiercapacityadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_EXTRA", "Approved Extra Capacity"),
                    ("REFUND_CSO", "Refunded CSO Capacity"),
                ],
                default="APPROVAL_EXTRA",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="identifiercapacityadjustment",
            name="helper_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="overflow",
            name="helper_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="overflow",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="overflow",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="overflow",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVE", "Approved"),
                    ("AUTO_CLOSE", "Auto Close"),
                    ("REFUND_OVERFLOW", "Refund Overflow"),
                    ("REFUND_TRANSACTION", "Refund Transaction"),
                    ("REFUND_TICKET", "Refund Ticket"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="overflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("TCSO", "Take Care Spill Over"),
                    ("CSO", "Completed Spill Over"),
                    ("RFND", "Refunded"),
                ],
                default="TCSO",
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="OverflowNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("PRE_CLOSE", "Pre-close pending overflow")],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "overflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.overflow",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overflow_notifications",
                        to="core.period",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="overflownotification",
            constraint=models.UniqueConstraint(
                fields=("overflow", "notification_type"),
                name="unique_overflow_notification_type",
            ),
        ),
    ]
