# Generated by Django 4.2.28 on 2026-02-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_overflow_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_overflow",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ledger",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="identifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.identifier",
            ),
        ),
        migrations.CreateModel(
            name="LedgerAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="core.ledger",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["ledger__priority"],
            },
        ),
    ]
