# Generated by Django 4.2.28 on 2026-02-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ticket_transaction_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.ticket",
            ),
        ),
    ]
