# Generated by Django 4.2.28 on 2026-04-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="core_passwo_selecto_7ec384_idx",
            old_name="core_passwo_selecto_6d6096_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="core_passwo_expires_71ae22_idx",
            old_name="core_passwo_expires_2d8a9b_idx",
        ),
    ]
