# Generated by Django 4.2.28 on 2026-04-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_transaction_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
