# Generated by Django 4.2.28 on 2026-04-14 13:29

from django.db import migrations, models
import django.db.models.deletion


def backfill_periods(apps, schema_editor):
    Ledger = apps.get_model("core", "Ledger")
    Period = apps.get_model("core", "Period")

    for ledger in Ledger.objects.all().iterator():
        period = Period.objects.create(
            name=f"{ledger.name} Period {ledger.pk}",
            start_date=ledger.created_at,
            end_date=ledger.end_date,
            is_open=ledger.is_active,
            closed_at=ledger.closed_at,
        )
        ledger.period_id = period.id
        ledger.save(update_fields=["period"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ledger_closed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_open", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="ledger",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledgers",
                to="core.period",
            ),
        ),
        migrations.RunPython(backfill_periods, migrations.RunPython.noop),
    ]
