# Generated by Django 4.2.28 on 2026-04-23 19:04

from django.db import migrations, models


def deduplicate_capacity_reserves(apps, schema_editor):
    Ledger = apps.get_model("core", "Ledger")
    LedgerAllocation = apps.get_model("core", "LedgerAllocation")

    reserve_keys = (
        Ledger.objects.filter(is_capacity_reserve=True)
        .values_list("period_id", "owner_id")
        .distinct()
    )

    for period_id, owner_id in reserve_keys:
        reserves = list(
            Ledger.objects.filter(
                period_id=period_id,
                owner_id=owner_id,
                is_capacity_reserve=True,
            ).order_by("id")
        )
        if len(reserves) <= 1:
            continue

        primary = reserves[0]
        for duplicate in reserves[1:]:
            LedgerAllocation.objects.filter(ledger_id=duplicate.id).update(ledger_id=primary.id)
            duplicate.delete()


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0010_identifiercapacityadjustment_owner_ledger_owner"),
    ]

    operations = [
        migrations.RunPython(deduplicate_capacity_reserves, noop_reverse),
        migrations.AddConstraint(
            model_name="ledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_capacity_reserve", True)),
                fields=("period", "owner"),
                name="unique_capacity_reserve_per_owner_period",
            ),
        ),
    ]
