# Generated by Django 4.2.28 on 2026-04-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_ledger_unique_capacity_reserve_per_owner_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentifierLedgerFreeze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applies_to_all", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_freezes",
                        to="core.identifier",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifier_freezes",
                        to="core.ledger",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifier_ledger_freezes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifier_ledger_freezes",
                        to="core.period",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="identifierledgerfreeze",
            constraint=models.UniqueConstraint(
                condition=models.Q(("applies_to_all", True)),
                fields=("identifier", "period", "owner"),
                name="unique_identifier_full_freeze_per_owner_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="identifierledgerfreeze",
            constraint=models.UniqueConstraint(
                condition=models.Q(("applies_to_all", False)),
                fields=("identifier", "period", "owner", "ledger"),
                name="unique_identifier_ledger_freeze_per_owner_period",
            ),
        ),
    ]
