# Generated by Django 4.2.28 on 2026-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_overflow_detached_overkill_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifiercapacityadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_EXTRA", "Approved Extra Capacity"),
                    ("REFUND_CSO", "Refunded CSO Capacity"),
                    ("REFUND_OVERKILL", "Refunded Overkill Capacity"),
                ],
                default="APPROVAL_EXTRA",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="overflow",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVE", "Approved"),
                    ("RESERVE_CONSUMED", "Reserve Consumed"),
                    ("AUTO_CLOSE", "Auto Close"),
                    ("REFUND_OVERFLOW", "Refund Overflow"),
                    ("REFUND_TRANSACTION", "Refund Transaction"),
                    ("REFUND_TICKET", "Refund Ticket"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="overflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("TCSO", "Take Care Spill Over"),
                    ("CSO", "Completed Spill Over"),
                    ("OVRK", "Overkill"),
                    ("RFND", "Refunded"),
                ],
                default="TCSO",
                max_length=4,
            ),
        ),
    ]
