# Generated by Django 4.2.28 on 2026-05-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_supportcase_supportmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="lucky_draw_reveal_time",
            field=models.TimeField(default=datetime.time(15, 30)),
        ),
    ]
