# Generated by Django 4.2.28 on 2026-05-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0019_period_pre_close_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Repeat Ticket",
                "verbose_name_plural": "Repeat Tickets",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepeatTicketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount_uses_allocation_basis", models.BooleanField(default=False)),
                ("use_permutations", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repeat_ticket_items",
                        to="core.identifier",
                    ),
                ),
                (
                    "repeat_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.repeatticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repeat Ticket Item",
                "verbose_name_plural": "Repeat Ticket Items",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="RepeatTicketGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("UNSUCCESSFUL", "Unsuccessful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_version", models.PositiveIntegerField(default=1)),
                ("failure_message", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_ticket_generations",
                        to="core.period",
                    ),
                ),
                (
                    "repeat_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to="core.repeatticket",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_generation",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repeat Ticket Generation",
                "verbose_name_plural": "Repeat Ticket Generations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="repeatticketgeneration",
            constraint=models.UniqueConstraint(
                fields=("repeat_ticket", "period"),
                name="unique_repeat_ticket_generation_per_period",
            ),
        ),
    ]
