# Generated by Django 4.2.28 on 2026-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportcase",
            name="intake_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("LOGIN_HELP", "Login help")],
                default="STANDARD",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="requester_login_identifier",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="requester_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
