# Generated by Django 4.2.28 on 2026-05-28 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0023_supportcase_intake_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportcase",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="OverrideResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selector",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["selector"], name="core_overri_selecto_52b4f2_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_overri_expires_def6b0_idx"
                    ),
                ],
            },
        ),
    ]
