# Generated by Django 4.2.28 on 2026-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_supportcase_options_overrideresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportcase",
            name="requester_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
